### ISSUE TITLE
Loading MPC comet file CometEls.txt fails.

### ISSUE THREAD

**Issue by Short-bus** [Short-bus/pilomar#93]
From @HOPKIRS21

When I run the program it gives me the following output:

```
pilomar 1.1.0

/usr/local/lib/python3.11/dist-packages/pandas/core/arrays/masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
from pandas.core import (
Hostname: Pilomar
Locale: ('en_US', 'UTF-8')
Using realtime clock.
Project root /home/*********/pilomar
Current time is: 2024-11-14 01:23:36.036666+00:00 UTC, offset is None seconds.
pilomar.py 2024-09-21 11:53:37
Main log to /home/*********/pilomar/log/pilomar_20241114012336.log
Camera log to /home/*********/pilomar/log/pilomar_camera_20241114012336.log
2024-11-14 01:23:36 RPi: Model: RPi 4 B 1.5 Num: 4 OStype: debian OSid: 12 OSname: bookworm OSbits: 64 OSproc: aarch64 SysKey: 4/bookworm/64
Removing out of date log files to preserve disc space...
find /home/*********/pilomar/log -type f -name 'pilomar_*.log' -mtime +2 -delete
Done.
2024-11-14 01:23:36 Loading parameters from file: /home/*********/pilomar/data/pilomar_params.json
Current UTC time is: 2024-11-14 01:23:36.090534+00:00
Local time is: 2024-11-13 20:23:36.090534-05:00
Python3 is UTF-8 compliant, make sure that the terminal is in UTF-8 mode too.
2024-11-14 01:23:36 Image storage: /
Camera enabled
2024-11-14 01:23:45 No recovery log file found for azimuth motor. Assuming 180.000°
2024-11-14 01:23:45 No recovery log file found for altitude motor. Assuming 000.000°
2024-11-14 01:23:45 Home location Latitude ********* N, Longitude ********* W
2024-11-14 01:23:45 Hipparcos data cache exists, using that.
2024-11-14 01:23:49 Loading Messier catalog from /home/*********/pilomar/data/messierobjects.json ...
2024-11-14 01:23:49 Loading constellation patterns...
2024-11-14 01:23:49 Loading New General Catalog (NGC) entries from /home/*********/pilomar/data/ngc.json ...
2024-11-14 01:23:49 NGC data cache exists, using that.
2024-11-14 01:23:49 Loading meteor shower list from /home/*********/pilomar/data/meteors.json ...
2024-11-14 01:23:49 Loading comet list from https://www.minorplanetcenter.net/iau/MPCORB/CometEls.txt ...
Traceback (most recent call last):
File "/home/*********/pilomar/src/pilomar.py", line 5112, in
comets = mpc.load_comets_dataframe(f) # Comet data loaded as a Pandas dataframe.
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/dist-packages/skyfield/data/mpc.py", line 186, in load_comets_dataframe
df = pd.read_csv(io.BytesIO(text), header=None, names=_COMET_FAST_COLUMNS)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/dist-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
return _read(filepath_or_buffer, kwds)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/dist-packages/pandas/io/parsers/readers.py", line 626, in _read
return parser.read(nrows)
^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/dist-packages/pandas/io/parsers/readers.py", line 1923, in read
) = self._engine.read( # type: ignore[attr-defined]
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/dist-packages/pandas/io/parsers/c_parser_wrapper.py", line 234, in read
chunks = self._reader.read_low_memory(nrows)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "parsers.pyx", line 838, in pandas._libs.parsers.TextReader.read_low_memory
File "parsers.pyx", line 905, in pandas._libs.parsers.TextReader._read_rows
File "parsers.pyx", line 874, in pandas._libs.parsers.TextReader._tokenize_rows
File "parsers.pyx", line 891, in pandas._libs.parsers.TextReader._check_tokenize_status
File "parsers.pyx", line 2061, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Expected 12 fields in line 584, saw 13
```

With the help of my one professors, we were able to bypass this issue. 
What we ended up changing was which column in the comet data was being used to sort them because there was an error in the reference column. 
We changed it to perihelion_year and it seems to have solved the issue. 
It may be possible that this would cause a problem later on, so if you have any other suggestions, I would love to hear them.

**Comment by Short-bus** [comment]
So far have not been able to recreate the error. However the Pandas version reported in the program output looks quite old (1.3.5). I think the installation script would currently install something like 1.5.3. Not sure if that's related at this point, but it's the only unusual message in the program output before the program fails.
Package versions can be checked from the 'Miscellaneous tools' menu, select 'About system' and check the final few lines of the output.

```
2024-11-21 17:00:23 Program: pilomar
2024-11-21 17:00:23 Program version: 1.2.0
2024-11-21 17:00:23 Project root: /home/pi/pilomar
2024-11-21 17:00:23 Microcontroller program version: 1.1.0 (good)
2024-11-21 17:00:23 Acceptable microcontroller versions: ['1.0', '1.1']
2024-11-21 17:00:23 Python version: sys.version_info(major=3, minor=11, micro=2, releaselevel='final', serial=0)
2024-11-21 17:00:23 Skyfield version: (1, 45)
2024-11-21 17:00:23 Astroalign version: 2.4.1
2024-11-21 17:00:23 Numpy version: 1.24.2
2024-11-21 17:00:23 Pandas version: 1.5.3
```
